### PR TITLE
[WIP] Fixes to dabo.ui.dGrid

### PR DESCRIPTION
**Pull request by mesalu**
# Various fixes to stabilize the dGrid class.

## Changes included are:
- Correct misuse of GridCellAttrs by reducing calls to `Clone`, Attrs, Renderers, and Editors are reference counted (poorly, in my opinion) at the wxWidgets level, and by not managing calls to `IncRef` and `DecRef` on them when expected (which, again, in my opinion is not always clear) it will lead to objects being prematurely freed, or not freed when expected. (Various seg faults + the "GetEventHandler() == this' wx assertion) (e0f72cd).  If you'd like to maintain use of Clone, you'll want to look into calling the correct wxReferenceCounter methods. (I found it overall easier to just clone less)
- Correct mismatched argspecs between a `CustomEditor` and `wx.grid.GridCellEditor` virtual methods.  These would throw a python exception on invocation (c++ side), which would then be muted by the translation back to c++ and a provide a null value where it was not expected. (af2acba)
- Add a __init__ method to the CustomEditors, this seems to resolve an issue where SIP would not find the custom editors `Create` method (leading to no Control within the Editor) (af2acba)
- Silence a deprecation warning (89e2d65)

## Other observed issues:
I'd like to address these before finalizing this PR
- Custom Editors lose properties after their first use
- Some other segfaults are lurking (haven't tracked down the issue yet)

### CODE REVIEW

**Comment by jfabiani** [comment]
something like this:

https://github.com/wxWidgets/wxPython/blob/master/demo/GridCustEditor.py

Johnf

**Comment by EdLeafe** [comment]
Sorry for taking so long to review - it's been a busy past few weeks. The changes look good.

**Comment by mesalu** [comment]
@EdLeafe 
I had intended to include some other changes before the PR was merged, but that's okay.

I've since made a change to reapply control properties in dGrid.__onWxGridEditorShown. I'll include that with the PR after I fix some renderer issues.

On the topic:
Is it safe to call `initProperties` on a dabo widget multiple times?

**Comment by EdLeafe** [comment]
It _shouldn't_ hurt, as invoking it should just set things to the same value. The only problem I can see is if later code changed the initial value of the properties, calling initProperties() again would change them back.

**Comment by mesalu** [comment]
Do you have a preferred method to use to restore properties to the widget?

**Comment by EdLeafe** [comment]
No, it would depend on the context. Normally you just do `Property = value`; if you had a bunch of them that you wanted to reset in a group, you could create a method that sets them, and then call that as needed. It really just depends on what it is that needs to happen.

**Pull request merged**
